a = open("shivam.txt")
print(a.readline())
a.seek(16)
print(a.readline())
a.seek(32)
print(a.readline())
a.close()
# a = open("shivam.txt")
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())
# print(a.readline())
# print(a.tell())